import type { Metadata } from "next";
import { Poppins, Source_Serif_4 } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import MotionProvider from "@/components/MotionProvider";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],
})

const serif = Source_Serif_4({
  subsets: ['latin'],
  variable: '--serif',
})

export const metadata: Metadata = {
  title: "Hivissual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className="h-full antialiased"
    >
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <body
        className={clsx(
          poppins.className,
          'relative',
          serif.variable
        )}
      >
        <MotionProvider>
          <Header />
          {children}
          <Footer />
        </MotionProvider>
      </body>
    </html>
  );
}
